require("dotenv").config();
const mongoose=require("mongoose"),Hotel=require("../models/Hotel"),User=require("../models/User");

const apiKey=process.env.GOOGLE_PLACES_API_KEY;
const ownerEmail=process.env.HOTEL_IMPORT_OWNER_EMAIL||"owner@travelmagnet.local";
const minimum=Math.max(100,Number(process.env.HOTEL_IMPORT_MINIMUM)||100);
const destinations=["Delhi","Chandigarh","Mumbai","Goa","Agra","Manali Himachal Pradesh","Shimla Himachal Pradesh","Dharamshala Himachal Pradesh","Dalhousie Himachal Pradesh","Kasol Himachal Pradesh","Mussoorie Uttarakhand","Nainital Uttarakhand","Rishikesh Uttarakhand","Auli Uttarakhand","Dehradun Uttarakhand"];
const fields=["places.id","places.displayName","places.formattedAddress","places.addressComponents","places.location","places.rating","places.userRatingCount","places.types","places.primaryTypeDisplayName","places.nationalPhoneNumber","places.websiteUri","places.googleMapsUri","places.businessStatus","places.priceLevel","places.parkingOptions","places.paymentOptions","places.accessibilityOptions","places.servesBreakfast","places.goodForChildren","places.allowsDogs","places.photos","nextPageToken"].join(",");
const slug=value=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const component=(place,type)=>place.addressComponents?.find(item=>item.types?.includes(type))?.longText;
const trueLabels=(object,labels)=>Object.entries(labels).filter(([key])=>object?.[key]===true).map(([,label])=>label);

async function search(textQuery,pageToken){const response=await fetch("https://places.googleapis.com/v1/places:searchText",{method:"POST",headers:{"Content-Type":"application/json","X-Goog-Api-Key":apiKey,"X-Goog-FieldMask":fields},body:JSON.stringify({textQuery,includedType:"lodging",languageCode:"en",regionCode:"IN",pageSize:20,...(pageToken?{pageToken}:{})})});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||`Google Places request failed (${response.status})`);return data}

function hotelData(place,owner){const city=component(place,"locality")||component(place,"administrative_area_level_2")||"India",state=component(place,"administrative_area_level_1"),pinCode=component(place,"postal_code"),parking=trueLabels(place.parkingOptions,{freeParkingLot:"Free parking",paidParkingLot:"Paid parking",freeStreetParking:"Free street parking",valetParking:"Valet parking",freeGarageParking:"Free garage parking",paidGarageParking:"Paid garage parking"}),accessibility=trueLabels(place.accessibilityOptions,{wheelchairAccessibleParking:"Wheelchair accessible parking",wheelchairAccessibleEntrance:"Wheelchair accessible entrance",wheelchairAccessibleRestroom:"Wheelchair accessible restroom",wheelchairAccessibleSeating:"Wheelchair accessible seating"}),services=[...(place.servesBreakfast?["Breakfast"]:[]),...(place.goodForChildren?["Good for children"]:[]),...(place.allowsDogs?["Allows dogs"]:[]),...parking,...accessibility],name=place.displayName?.text||"Hotel";return{owner,name,slug:`${slug(name)}-${place.id.slice(-8).toLowerCase()}`,shortDescription:`${name} is a lodging property in ${city}${state?`, ${state}`:""}. Property details were imported from Google Places and require owner verification.`,description:`Public property information for ${name}. Room inventory, rates, views and policies must be verified and completed by the hotel owner before publication.`,propertyType:place.primaryTypeDisplayName?.text||"Hotel",address:place.formattedAddress,city,state,country:"India",pinCode,location:{type:"Point",coordinates:[place.location?.longitude||0,place.location?.latitude||0]},contactNumber:place.nationalPhoneNumber,amenities:[...new Set(services)],source:"google_places",sourceMetadata:{googlePlaceId:place.id,googleMapsUri:place.googleMapsUri,websiteUri:place.websiteUri,businessStatus:place.businessStatus,userRatingCount:place.userRatingCount||0,priceLevel:place.priceLevel,types:place.types||[],parkingOptions:place.parkingOptions,paymentOptions:place.paymentOptions,accessibilityOptions:place.accessibilityOptions,photoResources:(place.photos||[]).slice(0,10).map(photo=>({widthPx:photo.widthPx,heightPx:photo.heightPx,authorAttributions:photo.authorAttributions||[]})),fetchedAt:new Date()},averageRating:place.rating||0,reviewCount:place.userRatingCount||0,approved:false,verificationStatus:"submitted",publicationStatus:"pending_approval",suspended:false}}

async function run(){if(!apiKey)throw new Error("GOOGLE_PLACES_API_KEY is required. Enable Places API (New) and billing first.");if(!process.env.MONGO_URI)throw new Error("MONGO_URI is required");await mongoose.connect(process.env.MONGO_URI);const owner=await User.findOne({email:ownerEmail,role:"vendor"});if(!owner)throw new Error(`Hotel import owner not found: ${ownerEmail}`);const unique=new Map();for(const destination of destinations){let token;for(let page=0;page<3;page++){const data=await search(`hotels in ${destination}, India`,token);for(const place of data.places||[])if(place.id)unique.set(place.id,place);token=data.nextPageToken;if(!token)break}console.log(`${destination}: ${unique.size} unique hotels collected`)}if(unique.size<minimum)throw new Error(`Only ${unique.size} unique hotels were returned; minimum is ${minimum}. No partial import was written.`);let imported=0;for(const place of unique.values()){const data=hotelData(place,owner._id);await Hotel.findOneAndUpdate({"sourceMetadata.googlePlaceId":place.id},{$set:data},{upsert:true,new:true,runValidators:true});imported++}console.log(`Imported ${imported} Google Places hotels as pending approval. No room, rate, view or policy data was invented.`);await mongoose.disconnect()}
run().catch(async error=>{console.error(error.message);await mongoose.disconnect().catch(()=>{});process.exit(1)});
