"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState, type ReactNode } from "react";
import { BadgeCheck, CalendarDays, IndianRupee, MapPin, Search, ShieldCheck, Sparkles, Star } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import WishlistButton, { useWishlist } from "@/components/hotels/WishlistButton";
import { apiRequest } from "@/lib/api";

type HotelCard={_id:string;slug:string;name:string;city:string;state?:string;images:string[];averageRating:number;reviewCount:number;startingPrice:number};
type Discovery={mostVisited:HotelCard[];beaches:HotelCard[];mountains:HotelCard[]};
const destinations=[
  {city:"Delhi",place:"India Gate",image:"https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=85"},
  {city:"Chandigarh",place:"Capitol Complex",image:"https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=85"},
  {city:"Mumbai",place:"Gateway of India",image:"https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=1200&q=85"},
  {city:"Goa",place:"Goa Beaches",image:"https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=85"},
  {city:"Agra",place:"Taj Mahal",image:"https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=85"},
];

export default function Home(){
  const router=useRouter(),wishlist=useWishlist();
  const[f,setF]=useState({destination:"Goa",checkIn:"",checkOut:"",adults:"2",children:"0",rooms:"1"});
  const[discovery,setDiscovery]=useState<Discovery>({mostVisited:[],beaches:[],mountains:[]});
  useEffect(()=>{apiRequest<Discovery>("/discover/hotels").then(setDiscovery).catch(()=>{})},[]);
  function submit(event:FormEvent){event.preventDefault();router.push(`/hotels?${new URLSearchParams(f)}`)}
  return <><Header/><main>
    <section className="relative flex min-h-[720px] items-center bg-[linear-gradient(90deg,rgba(3,17,35,.95),rgba(3,17,35,.48)),url('https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2000&q=88')] bg-cover bg-center px-4 pt-20 text-white"><div className="mx-auto w-full max-w-7xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2"><Sparkles size={16}/>Trusted stays across India</span><h1 className="mt-6 max-w-4xl text-5xl font-black leading-tight sm:text-7xl">Find your perfect stay with confidence.</h1><p className="mt-5 max-w-2xl text-xl text-slate-200">Verified properties, real room inventory and complete pricing before you pay.</p><form id="hotel-search" onSubmit={submit} className="mt-10 grid gap-3 rounded-3xl bg-white p-4 text-slate-900 shadow-2xl lg:grid-cols-[1.4fr_1fr_1fr_.7fr_.7fr_auto]"><Field icon={<MapPin/>} label="Destination" value={f.destination} set={value=>setF({...f,destination:value})}/><Field icon={<CalendarDays/>} label="Check-in" type="date" value={f.checkIn} set={value=>setF({...f,checkIn:value})}/><Field icon={<CalendarDays/>} label="Check-out" type="date" value={f.checkOut} set={value=>setF({...f,checkOut:value})}/><Field label="Adults" type="number" value={f.adults} set={value=>setF({...f,adults:value})}/><Field label="Rooms" type="number" value={f.rooms} set={value=>setF({...f,rooms:value})}/><button className="tm-button"><Search/>Search</button></form></div></section>
    <div className="bg-slate-50 py-20 dark:bg-slate-950"><DiscoverySection eyebrow="Popular choices" title="Most Visited Hotels" description="Stays travellers book and review most often." hotels={discovery.mostVisited} wishlist={wishlist}/><DiscoverySection eyebrow="Coastal stays" title="Beaches" description="Hotels close to beaches, coastlines and seaside destinations." hotels={discovery.beaches} wishlist={wishlist}/><DiscoverySection eyebrow="Fresh mountain air" title="Mountains" description="Relaxing stays around hills and Himalayan destinations." hotels={discovery.mountains} wishlist={wishlist}/></div>
    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-6"><div className="text-center"><p className="font-bold uppercase tracking-[.2em] text-sky-600">Explore India</p><h2 className="mt-3 text-4xl font-black">Top Destinations in India</h2><p className="mx-auto mt-3 max-w-2xl text-slate-500">Discover iconic places and find verified hotels nearby.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{destinations.map(destination=><button key={destination.city} type="button" onClick={()=>{setF(current=>({...current,destination:destination.city}));document.getElementById("hotel-search")?.scrollIntoView({behavior:"smooth",block:"center"})}} className="group relative h-80 overflow-hidden rounded-3xl text-left text-white shadow-lg"><Image src={destination.image} alt={`${destination.place}, ${destination.city}`} fill className="object-cover transition duration-500 group-hover:scale-110"/><span className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/20 to-transparent"/><span className="absolute inset-x-0 bottom-0 p-5"><span className="block text-2xl font-black">{destination.city}</span><span className="mt-1 block text-sm text-slate-200">{destination.place}</span><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold uppercase tracking-wider text-cyan-300">Explore hotels <Search size={14}/></span></span></button>)}</div></section>
    <section className="mx-auto max-w-7xl px-6 py-24"><div className="text-center"><p className="font-bold uppercase tracking-widest text-sky-600">Why TravelMagnet</p><h2 className="mt-3 text-4xl font-black">Booking without surprises</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[[BadgeCheck,"Verified properties","Admin-reviewed identity, property and safety information."],[IndianRupee,"Transparent pricing","Room, tax, platform fee and deposit shown before payment."],[ShieldCheck,"Protected inventory","Temporary holds and verified payment webhooks prevent double booking."]].map(([Icon,title,text])=><article key={title as string} className="tm-card p-7"><span className="grid size-14 place-items-center rounded-2xl bg-sky-50 text-sky-600 dark:bg-sky-500/10">{typeof Icon!=="string"&&<Icon/>}</span><h3 className="mt-5 text-xl font-black">{title as string}</h3><p className="mt-3 leading-7 text-slate-500">{text as string}</p></article>)}</div></section>
  </main><Footer/></>;
}

function DiscoverySection({eyebrow,title,description,hotels,wishlist}:{eyebrow:string;title:string;description:string;hotels:HotelCard[];wishlist:ReturnType<typeof useWishlist>}){return <section className="mx-auto max-w-7xl px-5 py-10 sm:px-6"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-sky-600">{eyebrow}</p><h2 className="mt-2 text-3xl font-black sm:text-4xl">{title}</h2><p className="mt-2 text-slate-500">{description}</p></div>{hotels.length?<div className="mt-7 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{hotels.map(hotel=><article key={hotel._id} className="tm-card group overflow-hidden"><div className="relative h-56 overflow-hidden"><Link href={`/hotels/${hotel.slug}`} aria-label={`View ${hotel.name}`} className="absolute inset-0 z-[1]"/><Image src={hotel.images?.[0]||"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80"} alt={hotel.name} fill className="object-cover transition duration-300 group-hover:scale-105"/><WishlistButton hotelId={hotel._id} active={wishlist.ids.has(hotel._id)} busy={wishlist.busy.has(hotel._id)} onToggle={wishlist.toggle} className="absolute right-3 top-3 z-10"/></div><Link href={`/hotels/${hotel.slug}`} className="block p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-lg font-black">{hotel.name}</h3><p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><MapPin size={14}/>{hotel.city}{hotel.state?`, ${hotel.state}`:""}</p></div><span className="flex shrink-0 items-center gap-1 rounded-lg bg-emerald-600 px-2 py-1 text-xs font-bold text-white"><Star size={12}/>{hotel.averageRating||"New"}</span></div><div className="mt-5 border-t border-slate-100 pt-4 dark:border-white/10"><small className="text-slate-500">Starting from</small><p className="text-xl font-black">{hotel.startingPrice?`₹${hotel.startingPrice.toLocaleString("en-IN")}`:"Check price"}<span className="ml-1 text-xs font-medium text-slate-500">/ night</span></p></div></Link></article>)}</div>:<div className="tm-card mt-7 p-8 text-center text-slate-500">No hotels are available in this category yet.</div>}</section>}

function Field({label,value,set,type="text",icon}:{label:string;value:string;set:(value:string)=>void;type?:string;icon?:ReactNode}){return <label className="rounded-xl bg-slate-50 px-3 py-2"><small className="block font-bold text-slate-500">{label}</small><span className="flex items-center gap-2">{icon}<input required type={type} min={type==="number"?1:undefined} value={value} onChange={event=>set(event.target.value)} className="min-w-0 bg-transparent py-1 outline-none"/></span></label>}
