const Booking=require("../models/Booking"),Payment=require("../models/Payment"),Refund=require("../models/Refund"),Notification=require("../models/Notification"),{createDedicatedBooking,releaseHold}=require("../services/bookingService");
const columns=[{key:"hotelName",label:"Hotel Name",defaultVisible:true,sortable:true,order:1,width:220},{key:"numberOfRooms",label:"No. of Rooms",defaultVisible:true,sortable:true,order:2,width:120},{key:"guestName",label:"Guest Name",defaultVisible:true,sortable:true,order:3,width:180},{key:"checkIn",label:"From Date",defaultVisible:true,sortable:true,order:4,width:150},{key:"checkOut",label:"To Date",defaultVisible:true,sortable:true,order:5,width:150},{key:"paymentStatus",label:"Payment Status",defaultVisible:true,sortable:true,order:6,width:150},{key:"totalAmount",label:"Amount",defaultVisible:true,sortable:true,order:7,width:120},{key:"bookingStatus",label:"Booking Status",defaultVisible:false,sortable:true,order:8,width:150},{key:"guests",label:"Number of Persons",defaultVisible:false,sortable:true,order:9,width:150}];
function listFilter(req,base){const q={...base},allowed=["pending","payment_processing","confirmed","checked_in","checked_out","completed","cancelled","refund_pending","refunded","disputed","no_show","failed"];if(req.query.status){if(!allowed.includes(req.query.status))throw Object.assign(new Error("Invalid booking status filter"),{statusCode:422});q.bookingStatus=req.query.status}if(req.query.paymentStatus){if(!["pending","paid","failed","refunded"].includes(req.query.paymentStatus))throw Object.assign(new Error("Invalid payment status filter"),{statusCode:422});q.paymentStatus=req.query.paymentStatus}if(req.query.from||req.query.to){q.createdAt={};if(req.query.from)q.createdAt.$gte=new Date(`${req.query.from}T00:00:00.000Z`);if(req.query.to)q.createdAt.$lte=new Date(`${req.query.to}T23:59:59.999Z`)}return q}
async function page(req,filter){const page=Math.max(1,Number(req.query.page)||1),perPage=Math.min(100,Math.max(1,Number(req.query.perPage)||10)),total=await Booking.countDocuments(filter),documents=await Booking.find(filter).populate("hotel","name").populate("user","name").sort("-createdAt").skip((page-1)*perPage).limit(perPage).lean(),rows=documents.map(row=>({_id:row._id,hotelName:row.hotel?.name||"Property unavailable",numberOfRooms:row.numberOfRooms,guestName:row.user?.name||row.guestDetails?.leadGuestName||"Guest",checkIn:row.checkIn,checkOut:row.checkOut,paymentStatus:row.paymentStatus,totalAmount:row.totalAmount,bookingStatus:row.bookingStatus,guests:row.guests}));return{rows,meta:{page,perPage,total,totalPages:Math.max(1,Math.ceil(total/perPage))},columns}}
async function create(req,res){const required=["hotelId","roomId","checkIn","checkOut","paymentMethod"];if(required.some(x=>!req.body[x]))return res.status(422).json({message:"Missing booking fields"});const b=await createDedicatedBooking({user:req.user,body:{...req.body,guests:req.body.guests||req.body.adults||1}});if(!b)return res.status(404).json({message:"Room not found"});await Notification.create({user:b.vendor,type:"new_booking",title:"New booking",message:`Booking ${b.invoiceNumber} received`,data:{bookingId:b._id}});res.status(201).json(b)}
async function mine(req,res){res.json(await page(req,listFilter(req,{user:req.user._id})))}
async function one(req,res){const q=req.user.role==="admin"?{_id:req.params.id}:req.user.role==="vendor"?{_id:req.params.id,vendor:req.user._id}:{_id:req.params.id,user:req.user._id},b=await Booking.findOne(q).populate("hotel","name city address images checkInTime checkOutTime").populate("roomType","name bedType images").populate("user","name email phone");if(!b)return res.status(404).json({message:"Booking not found"});res.json(b)}
async function cancel(req,res){const b=await Booking.findOne({_id:req.params.id,user:req.user._id});if(!b)return res.status(404).json({message:"Booking not found"});if(!["pending","confirmed"].includes(b.bookingStatus))return res.status(409).json({message:"Booking cannot be cancelled"});b.bookingStatus="cancelled";b.statusHistory.push({status:"cancelled",actor:req.user._id,note:req.body.reason});await releaseHold(b);if(b.paymentStatus==="paid"){const p=await Payment.findOne({booking:b._id}),amount=Math.min(b.priceSnapshot?.refundableAmount||b.totalAmount,p?.paidAmount||0);await Refund.findOneAndUpdate({booking:b._id},{$setOnInsert:{booking:b._id,payment:p?._id,customer:req.user._id,amount,reason:req.body.reason,history:[{status:"requested",actor:req.user._id}]}},{upsert:true});b.bookingStatus="refund_pending";await b.save()}res.json(b)}
async function ownerList(req,res){res.json(await page(req,listFilter(req,req.user.role==="admin"?{}:{vendor:req.user._id})))}
async function status(req,res){const q=req.user.role==="admin"?{_id:req.params.id}:{_id:req.params.id,vendor:req.user._id},b=await Booking.findOne(q);if(!b)return res.status(404).json({message:"Booking not found"});const flow={pending:["confirmed","cancelled"],confirmed:["checked_in","cancelled","no_show"],checked_in:["checked_out"],checked_out:["completed"]};if(!flow[b.bookingStatus]?.includes(req.body.status))return res.status(409).json({message:"Invalid status transition"});b.bookingStatus=req.body.status;b.statusHistory.push({status:req.body.status,actor:req.user._id,note:req.body.note});if(req.body.status==="cancelled")await releaseHold(b);else await b.save();res.json(b)}module.exports={create,mine,one,cancel,ownerList,status,columns,listFilter};
