const Booking=require("../models/Booking");
const bookingFields=Object.freeze({invoiceNumber:"Booking No.",createdAt:"Booked At",checkIn:"Check-in",checkOut:"Check-out",bookingStatus:"Booking Status",paymentStatus:"Payment Status",totalAmount:"Total Amount",numberOfRooms:"Rooms",nights:"Nights","hotel.name":"Hotel","user.name":"Guest","user.email":"Guest Email"});
const escapeCsv=value=>{const text=value instanceof Date?value.toISOString():String(value??"");return `"${text.replace(/"/g,'""')}"`};
const get=(row,path)=>path.split(".").reduce((value,key)=>value?.[key],row);
function bookingFilter(req){const filter=req.user.role==="admin"?{}:req.user.role==="vendor"?{vendor:req.user._id}:{user:req.user._id};if(req.query.status)filter.bookingStatus=req.query.status;if(req.query.paymentStatus)filter.paymentStatus=req.query.paymentStatus;if(req.query.hotel){if(req.user.role==="user")throw Object.assign(new Error("Hotel filtering is not available for customer exports"),{statusCode:422});filter.hotel=req.query.hotel}if(req.query.from||req.query.to){filter.createdAt={};if(req.query.from)filter.createdAt.$gte=new Date(`${req.query.from}T00:00:00.000Z`);if(req.query.to)filter.createdAt.$lte=new Date(`${req.query.to}T23:59:59.999Z`)}return filter}
function fields(req){const selected=String(req.query.fields||"").split(",").filter(Boolean);const keys=selected.length?selected:Object.keys(bookingFields).filter(key=>!["user.email"].includes(key));if(keys.some(key=>!bookingFields[key]))throw Object.assign(new Error("One or more export fields are not allowed"),{statusCode:422});return keys}
async function definition(req,res){res.json({type:"bookings",fields:Object.entries(bookingFields).map(([key,label])=>({key,label,defaultSelected:key!=="user.email"}))})}
async function bookings(req,res){const keys=fields(req),rows=await Booking.find(bookingFilter(req)).populate("hotel","name").populate("user","name email").sort("-createdAt").limit(10000).lean(),csv=[keys.map(key=>escapeCsv(bookingFields[key])).join(","),...rows.map(row=>keys.map(key=>escapeCsv(get(row,key))).join(","))].join("\r\n");res.set({"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="bookings-${new Date().toISOString().slice(0,10)}.csv"`,"Cache-Control":"private, no-store"}).send(`\uFEFF${csv}`)}
module.exports={definition,bookings,bookingFields,bookingFilter};
