"use client";

import Image from "next/image";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BadgeCheck, BedDouble, CalendarDays, Check, Clock3, IndianRupee, MapPin, ShieldCheck, Star, Users } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { apiRequest } from "@/lib/api";
import { Empty, ErrorState, Loading } from "@/components/common/States";
import WishlistButton, { useWishlist } from "@/components/hotels/WishlistButton";

type Room={_id:string;name:string;roomType?:string;description?:string;maximumGuests:number;maximumAdults?:number;maximumChildren?:number;bedType?:string;numberOfBeds?:number;roomSize?:number;roomView?:string;smokingStatus?:string;airConditioning?:boolean;attachedBathroom?:boolean;amenities?:string[];images?:string[];bathroomImages?:string[];basePrice:number;discountedPrice?:number;taxes?:number;totalRooms:number};
type Review={_id:string;rating:number;comment?:string;user?:{name?:string};createdAt?:string};
type Hotel={_id:string;slug:string;name:string;shortDescription?:string;description?:string;propertyType?:string;starRating?:number;address?:string;city:string;state?:string;country?:string;images?:string[];averageRating:number;reviewCount:number;verificationBadges?:string[];amenities?:string[];nearbyLandmarks?:string[];checkInTime?:string;checkOutTime?:string;cancellationPolicy?:string;paymentPolicy?:string;petPolicy?:string;smokingPolicy?:string;houseRules?:string[];parkingInformation?:string;accessibilityInformation?:string;receptionAvailability?:string;coupleFriendly?:boolean;familyFriendly?:boolean;businessFriendly?:boolean;rooms:Room[];reviews?:Review[]};
type Quote={nights:number;subtotal:number;discountAmount?:number;taxAmount?:number;finalAmount:number};
const fallback="https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1500&q=85";

export default function Details({slug}:{slug:string}){
  const params=useSearchParams()!,wishlist=useWishlist();
  const[hotel,setHotel]=useState<Hotel|null>(null),[quotes,setQuotes]=useState<Record<string,Quote>>({}),[error,setError]=useState(""),[quoteLoading,setQuoteLoading]=useState(false);
  const[search,setSearch]=useState({checkIn:params.get("checkIn")||"",checkOut:params.get("checkOut")||"",adults:params.get("adults")||"2",children:params.get("children")||"0",rooms:params.get("rooms")||"1"});
  const load=useCallback(async()=>{setError("");try{setHotel(await apiRequest<Hotel>(`/search/hotels/${slug}`))}catch(cause){setError(cause instanceof Error?cause.message:"Hotel is unavailable")}},[slug]);
  useEffect(()=>{void load()},[load]);
  const validDates=Boolean(search.checkIn&&search.checkOut&&search.checkOut>search.checkIn);
  const query=useMemo(()=>new URLSearchParams(search).toString(),[search]);
  useEffect(()=>{if(!hotel||!validDates){setQuotes({});return}let active=true;setQuoteLoading(true);Promise.all(hotel.rooms.map(async room=>[room._id,await apiRequest<Quote>(`/search/quote/${room._id}?${query}`)] as const)).then(rows=>{if(active)setQuotes(Object.fromEntries(rows))}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Prices could not be loaded")}).finally(()=>{if(active)setQuoteLoading(false)});return()=>{active=false}},[hotel,query,validDates]);
  if(error&&!hotel)return <><Header/><main className="min-h-screen px-5 pt-28"><ErrorState message={error} retry={()=>void load()}/></main><Footer/></>;
  if(!hotel)return <div className="min-h-screen bg-slate-50 pt-24 dark:bg-slate-950"><Loading/></div>;
  const gallery=[...(hotel.images||[]),...hotel.rooms.flatMap(room=>room.images||[])].filter(Boolean).slice(0,5),hero=gallery[0]||fallback;
  return <><Header/><main className="min-h-screen bg-slate-50 pb-20 pt-24 dark:bg-slate-950"><div className="mx-auto max-w-7xl px-5">
    <section className="grid h-[520px] gap-2 overflow-hidden rounded-3xl md:grid-cols-2"><div className="relative min-h-72"><Image src={hero} alt={hotel.name} fill priority className="object-cover"/><WishlistButton hotelId={hotel._id} active={wishlist.ids.has(hotel._id)} busy={wishlist.busy.has(hotel._id)} onToggle={wishlist.toggle} className="absolute right-5 top-5 z-10"/></div><div className="hidden grid-cols-2 gap-2 md:grid">{Array.from({length:4},(_,index)=><div key={index} className="relative overflow-hidden"><Image src={gallery[index+1]||hero} alt={`${hotel.name} photo ${index+2}`} fill className="object-cover"/></div>)}</div></section>
    <section className="mt-8 grid gap-7 lg:grid-cols-[1fr_360px]"><div><div className="flex flex-wrap gap-2">{(hotel.verificationBadges||[]).map(badge=><span key={badge} className="rounded-full bg-teal-100 px-3 py-1 text-xs font-bold capitalize text-teal-700"><BadgeCheck className="mr-1 inline" size={14}/>{badge.replaceAll("_"," ")}</span>)}</div><p className="mt-4 text-sm font-bold uppercase tracking-widest text-sky-600">{hotel.propertyType||"Hotel"}</p><h1 className="mt-1 text-4xl font-black sm:text-5xl">{hotel.name}</h1><p className="mt-3 flex items-start gap-2 text-slate-500"><MapPin className="mt-0.5 shrink-0" size={19}/>{hotel.address||[hotel.city,hotel.state,hotel.country].filter(Boolean).join(", ")}</p><div className="mt-5 flex flex-wrap gap-4 text-sm font-semibold"><span className="flex items-center gap-1"><Star size={17} className="text-amber-500" fill="currentColor"/>{hotel.averageRating||"New"} ({hotel.reviewCount||0} reviews)</span><span className="flex items-center gap-1"><Clock3 size={17}/>Check-in {hotel.checkInTime||"14:00"}</span><span className="flex items-center gap-1"><Clock3 size={17}/>Check-out {hotel.checkOutTime||"11:00"}</span></div><p className="mt-7 max-w-4xl leading-8 text-slate-600 dark:text-slate-300">{hotel.description||hotel.shortDescription||"Property information will be updated by the hotel owner."}</p></div>
      <aside className="tm-card h-fit p-5"><h2 className="text-lg font-black">Check room prices</h2><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-500">Check-in<input type="date" value={search.checkIn} onChange={event=>setSearch({...search,checkIn:event.target.value})} className="tm-input mt-1 px-3 py-2"/></label><label className="text-xs font-bold text-slate-500">Check-out<input type="date" min={search.checkIn||undefined} value={search.checkOut} onChange={event=>setSearch({...search,checkOut:event.target.value})} className="tm-input mt-1 px-3 py-2"/></label><label className="text-xs font-bold text-slate-500">Adults<input type="number" min="1" value={search.adults} onChange={event=>setSearch({...search,adults:event.target.value})} className="tm-input mt-1 px-3 py-2"/></label><label className="text-xs font-bold text-slate-500">Rooms<input type="number" min="1" value={search.rooms} onChange={event=>setSearch({...search,rooms:event.target.value})} className="tm-input mt-1 px-3 py-2"/></label></div><p className="mt-4 text-xs text-slate-500">Select valid dates to view availability, taxes and total stay price.</p></aside>
    </section>
    <section className="mt-12"><h2 className="text-2xl font-black">Facilities & amenities</h2>{hotel.amenities?.length?<div className="mt-5 grid gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">{hotel.amenities.map(item=><div key={item} className="tm-card flex items-center gap-3 p-4 text-sm font-semibold"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10"><Check size={17}/></span>{item}</div>)}</div>:<p className="mt-3 text-slate-500">Facilities will be updated by the property.</p>}</section>
    {hotel.nearbyLandmarks?.length?<section className="mt-12"><h2 className="text-2xl font-black">Nearby landmarks</h2><div className="mt-4 flex flex-wrap gap-3">{hotel.nearbyLandmarks.map(item=><span key={item} className="rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold dark:border-white/10 dark:bg-slate-900"><MapPin className="mr-1 inline" size={15}/>{item}</span>)}</div></section>:null}
    <section id="rooms" className="mt-14"><div><p className="font-bold uppercase tracking-widest text-sky-600">Stay options</p><h2 className="mt-2 text-3xl font-black">Rooms & prices</h2></div>{hotel.rooms.length?<div className="mt-6 space-y-6">{hotel.rooms.map(room=>{const quote=quotes[room._id],roomImage=room.images?.[0]||hero,bookingQuery=new URLSearchParams({...search,hotel:hotel._id,room:room._id}).toString();return <article key={room._id} className="tm-card overflow-hidden lg:grid lg:grid-cols-[300px_1fr_260px]"><div className="relative min-h-64"><Image src={roomImage} alt={room.name} fill className="object-cover"/></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-sky-600">{room.roomType||"Room"}</p><h3 className="mt-1 text-2xl font-black">{room.name}</h3><div className="mt-3 flex flex-wrap gap-4 text-sm text-slate-500"><span className="flex items-center gap-1"><Users size={16}/>{room.maximumGuests} guests</span><span className="flex items-center gap-1"><BedDouble size={16}/>{room.numberOfBeds||1} {room.bedType||"bed"}</span>{room.roomSize&&<span>{room.roomSize} sq. ft.</span>}{room.roomView&&<span>{room.roomView} view</span>}</div>{room.description&&<p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">{room.description}</p>}<div className="mt-4 flex flex-wrap gap-2">{(room.amenities||[]).slice(0,8).map(item=><span key={item} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold dark:bg-white/10">{item}</span>)}</div></div><div className="flex flex-col justify-center border-t border-slate-200 p-6 lg:border-l lg:border-t-0 dark:border-white/10"><small className="text-slate-500">{quote?`${quote.nights} night total`:"Price per night"}</small>{room.discountedPrice&&!quote&&<span className="mt-1 text-sm text-slate-400 line-through">₹{room.basePrice.toLocaleString("en-IN")}</span>}<strong className="mt-1 text-3xl font-black">₹{(quote?.finalAmount||room.discountedPrice||room.basePrice).toLocaleString("en-IN")}</strong>{quote&&<p className="mt-2 text-xs text-slate-500">Taxes included in total</p>}<Link href={validDates?`/checkout?${bookingQuery}`:"#rooms"} aria-disabled={!validDates} className={`tm-button mt-5 ${!validDates?"pointer-events-none opacity-50":""}`}>{quoteLoading?"Checking...":"Book now"}</Link>{!validDates&&<p className="mt-2 text-center text-xs text-amber-600">Select dates first</p>}</div></article>})}</div>:<div className="mt-6"><Empty title="Rooms are being updated" text="This property has not published bookable room inventory yet."/></div>}</section>
    <section className="mt-14 grid gap-6 lg:grid-cols-2"><div className="tm-card p-6"><h2 className="flex items-center gap-2 text-xl font-black"><ShieldCheck className="text-sky-600"/>Property policies</h2><dl className="mt-5 space-y-4 text-sm"><Policy title="Cancellation" value={hotel.cancellationPolicy}/><Policy title="Payment" value={hotel.paymentPolicy}/><Policy title="Pets" value={hotel.petPolicy}/><Policy title="Smoking" value={hotel.smokingPolicy}/><Policy title="Parking" value={hotel.parkingInformation}/></dl></div><div className="tm-card p-6"><h2 className="text-xl font-black">Good to know</h2><div className="mt-5 flex flex-wrap gap-2">{hotel.familyFriendly&&<Tag text="Family friendly"/>}{hotel.coupleFriendly&&<Tag text="Couple friendly"/>}{hotel.businessFriendly&&<Tag text="Business friendly"/>}{hotel.receptionAvailability&&<Tag text={hotel.receptionAvailability}/>}</div>{hotel.houseRules?.length?<ul className="mt-5 space-y-2 text-sm text-slate-600 dark:text-slate-300">{hotel.houseRules.map(rule=><li key={rule} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-emerald-600"/>{rule}</li>)}</ul>:<p className="mt-4 text-sm text-slate-500">Contact the property for additional house rules.</p>}</div></section>
    {hotel.reviews?.length?<section className="mt-14"><h2 className="text-2xl font-black">Guest reviews</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{hotel.reviews.slice(0,6).map(review=><article key={review._id} className="tm-card p-5"><div className="flex justify-between"><strong>{review.user?.name||"Verified guest"}</strong><span className="flex items-center gap-1 font-bold text-amber-600"><Star size={15} fill="currentColor"/>{review.rating}</span></div><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{review.comment||"Rated this stay."}</p></article>)}</div></section>:null}
  </div></main><Footer/></>;
}

function Policy({title,value}:{title:string;value?:string}){return <div><dt className="font-bold">{title}</dt><dd className="mt-1 text-slate-500">{value||"Contact the property for details."}</dd></div>}
function Tag({text}:{text:string}){return <span className="rounded-full bg-sky-50 px-3 py-1.5 text-xs font-bold text-sky-700 dark:bg-sky-500/10 dark:text-sky-300">{text}</span>}
