"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { apiRequest } from "@/lib/api";

type Audience="admin"|"vendor"|"user";
type Role={_id:string;name:string;description?:string;audience:Audience;permissions:string[];active:boolean;system?:boolean};
type PermissionGroup={audience:Audience;pages:{key:string;label:string}[];operations:{key:string;label:string}[]};
type Account={_id:string;name:string;email:string;role:Audience;status:string;accessRole?:{_id:string;name:string}};
const labels:Record<Audience,string>={admin:"Hotel Admin",vendor:"Hotel Owner",user:"User"};

export default function RolesPermissions(){
  const [roles,setRoles]=useState<Role[]>([]),[catalog,setCatalog]=useState<PermissionGroup[]>([]),[users,setUsers]=useState<Account[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [form,setForm]=useState<{id?:string;name:string;description:string;audience:Audience;permissions:string[];active:boolean}>({name:"",description:"",audience:"vendor",permissions:[],active:true});
  const load=useCallback(async()=>{try{const[r,c,u]=await Promise.all([apiRequest<Role[]>("/admin/roles"),apiRequest<PermissionGroup[]>("/admin/permission-catalog"),apiRequest<Account[]>("/admin/role-users")]);setRoles(r);setCatalog(c);setUsers(u)}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load roles")}},[]);
  useEffect(()=>{void load()},[load]);
  const group=useMemo(()=>catalog.find(item=>item.audience===form.audience),[catalog,form.audience]);
  function audience(value:Audience){setForm(current=>({...current,audience:value,permissions:[],id:undefined}))}
  function toggle(key:string){setForm(current=>({...current,permissions:current.permissions.includes(key)?current.permissions.filter(item=>item!==key):[...current.permissions,key]}))}
  async function save(event:FormEvent){event.preventDefault();setError("");try{await apiRequest(form.id?`/admin/roles/${form.id}`:"/admin/roles",{method:form.id?"PUT":"POST",body:JSON.stringify(form)});setNotice(form.id?"Role updated successfully.":"Role created successfully.");setForm({name:"",description:"",audience:form.audience,permissions:[],active:true});await load()}catch(cause){setError(cause instanceof Error?cause.message:"Role could not be saved")}}
  function edit(role:Role){setForm({id:role._id,name:role.name,description:role.description||"",audience:role.audience,permissions:role.permissions||[],active:role.active});window.scrollTo({top:0,behavior:"smooth"})}
  async function assign(userId:string,roleId:string){setError("");try{await apiRequest(`/admin/role-users/${userId}`,{method:"PUT",body:JSON.stringify({roleId:roleId||null})});setNotice("User access updated.");await load()}catch(cause){setError(cause instanceof Error?cause.message:"Role could not be assigned")}}
  return <main className="min-h-screen bg-slate-50 p-5 dark:bg-slate-950 sm:p-8"><div className="mx-auto max-w-7xl space-y-7"><div><h1 className="text-3xl font-black">Roles & Permissions</h1><p className="mt-2 text-slate-500">Create page access roles for hotel admins, hotel owners and users, then assign them to accounts.</p></div>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300">{notice}</p>}
  <form onSubmit={save} className="tm-card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">{form.id?"Edit role":"Add role"}</h2><p className="mt-1 text-sm text-slate-500">Choose which pages and operations this role can use.</p></div>{form.id&&<button type="button" className="tm-secondary" onClick={()=>setForm({name:"",description:"",audience:"vendor",permissions:[],active:true})}>Cancel edit</button>}</div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Role name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="tm-input mt-2" placeholder="e.g. Front Desk Manager"/></label><label className="text-sm font-bold">Account type<select value={form.audience} disabled={Boolean(form.id)} onChange={e=>audience(e.target.value as Audience)} className="tm-input mt-2"><option value="admin">Hotel Admin</option><option value="vendor">Hotel Owner</option><option value="user">User</option></select></label><label className="text-sm font-bold">Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="tm-input mt-2" placeholder="What this role is for"/></label></div>
  <div className="mt-6"><h3 className="font-black">Visible pages</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{group?.pages.map(item=><label key={item.key} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 text-sm capitalize dark:border-white/10"><input type="checkbox" checked={form.permissions.includes(item.key)} onChange={()=>toggle(item.key)} className="size-4 accent-sky-600"/>{item.label}</label>)}</div></div>
  <details className="mt-6"><summary className="cursor-pointer font-black">Action permissions</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{group?.operations.map(item=><label key={item.key} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 text-sm dark:border-white/10"><input type="checkbox" checked={form.permissions.includes(item.key)} onChange={()=>toggle(item.key)} className="size-4 accent-sky-600"/>{item.label}</label>)}</div></details><div className="mt-6 flex items-center gap-4"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Active role</label><button className="tm-button">{form.id?"Save changes":"Create role"}</button></div></form>
  <section className="tm-card overflow-hidden"><div className="border-b border-slate-200 p-5 dark:border-white/10"><h2 className="text-xl font-black">Created roles</h2></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{roles.map(role=><article key={role._id} className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><div className="flex justify-between gap-3"><div><h3 className="font-black">{role.name}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wide text-sky-600">{labels[role.audience]}</p></div><button type="button" onClick={()=>edit(role)} className="text-sm font-bold text-sky-600">Edit</button></div><p className="mt-3 text-sm text-slate-500">{role.description||"No description"}</p><p className="mt-3 text-xs font-semibold text-slate-500">{role.permissions.length} permissions · {role.active?"Active":"Inactive"}</p></article>)}</div></section>
  <section className="tm-card overflow-hidden"><div className="border-b border-slate-200 p-5 dark:border-white/10"><h2 className="text-xl font-black">Assign roles to users</h2><p className="mt-1 text-sm text-slate-500">Only roles matching the account type can be assigned.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-white/5"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Email</th><th className="px-5 py-3">Account type</th><th className="px-5 py-3">Access role</th></tr></thead><tbody>{users.map(user=><tr key={user._id} className="border-t border-slate-100 dark:border-white/10"><td className="px-5 py-3 font-bold">{user.name}</td><td className="px-5 py-3 text-slate-500">{user.email}</td><td className="px-5 py-3">{labels[user.role]}</td><td className="px-5 py-3"><select aria-label={`Role for ${user.name}`} value={user.accessRole?._id||""} onChange={e=>void assign(user._id,e.target.value)} className="tm-input max-w-64 py-2"><option value="">Default access</option>{roles.filter(role=>role.audience===user.role&&role.active).map(role=><option key={role._id} value={role._id}>{role.name}</option>)}</select></td></tr>)}</tbody></table></div></section></div></main>
}
